title: Sadiq Khoja # The title of the blog
author: Sadiq Khoja # Your name 
email: sadiqkhoja@gmail.com # your email shown in the footer
url: https://www.sadiqkhoja.com # this is your site's root address.
description: > # this means to ignore newlines until "show_excerpts:"
  Learn - Enjoy - Contribute
favicon: "./favicon.ico" # set the favicon of the site 

show_excerpts: false # set to true to show excerpts on the homepage
  
# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  avatar_url: "https://www.gravatar.com/avatar/636a764bfb906bc2c64583bf36cbd653?s=128" # avatar in about page
  about_you: Senior Consultant @ Deloitte # short description about you in about page
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

  # generate social links in about page.
  social_links:
    twitter: sadiqkhoja
    github:  sadiqkhoja
    rss: RSS
    # dribbble: 
    #facebook: huangyz0918
    # flickr:   
    # instagram: 
    linkedin: sadiqkhoja
    # pinterest: 
    # youtube: 
    # youtube_channel: 
    # youtube_channel_name: 
    # telegram: 
    # googleplus: 
    # microdotblog: 
    # reddit: 

    # Mastodon instances
    # mastodon:
    # - username: 
    #   instance: 
    # - username: 
    #   instance: 

# Build settings
remote_theme: huangyz0918/moving # note, please use huangyz0918/moving if you want to publish to Github Pages.
#theme: moving

plugins:
  - jekyll-feed
  - jekyll-seo-tag
